# Generated by Django 3.0.6 on 2020-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardclass',
            name='name',
            field=models.CharField(default='Primary', max_length=64),
            preserve_default=False,
        ),
    ]
