# Generated by Django 3.0.6 on 2020-06-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200619_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cardClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.CardClass'),
            preserve_default=False,
        ),
    ]
