# Generated by Django 2.0.3 on 2020-06-27 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200627_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
