# Generated by Django 2.0.3 on 2020-06-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('cardClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CardClass')),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.RequestStatus'),
        ),
    ]
